[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pygidata"
version = "0.5.3"
description = "Python package providing an interface to the Gantner Instruments Data API"
readme = "README.md"
authors = [{ name = "Gantner Instruments GmbH" }]
requires-python = ">=3.10,<3.15"
keywords = ["python", "ginsutility=1.18.0"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Operating System :: Unix",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows"
]
dynamic = ["dependencies"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["pygidata*", "gi_data*", "ginsutility*"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[project.optional-dependencies]
test = ["pytest", "pytest-xdist"]
ginsutility = [
  "dash",
  "matplotlib",
  "numpy",
  "pandas",
  "plotly",
  "sip>=6.7",
  "PyQt5==5.15.11",
  "pyqtgraph",
]

[tool.tox]
env_list = ["py310", "py311", "py312", "py313", "py314"]

[tool.tox.env_run_base]
deps = [
  "pytest>=7",
  "pytest-xdist",
]
commands = [
  ["pytest", "-q"]
]
package = "wheel"
