version: '3'

services:
  lab:
    image: my_docker
    volumes:
     - ./notebooks/:/notebooks
    ports:
      - "8888:8888"
    environment:
            JUPYTER_ENABLE_LAB: 1
            GRANT_SUDO: "yes"
    user: root
    command: start-notebook.sh --ip=0.0.0.0 --NotebookApp.notebook_dir=/notebook --NotebookApp.token=''
